sidebar:
  title: "&aSimpleSidebar"
  update-interval: 20
  lines:
    - "&7Игрок: &f%player%"
    - "&7Онлайн: &a%online%"
    - "&7Мир: &b%world%"
tab:
  enabled: true
  header:
    - строка
    - строка
  footer:
    - строка
    - строка
